### ISSUE TITLE
上传失败，请在高级配置中填写启动命令

### ISSUE THREAD

**Issue by beader** [avtion/bark-serverless#1]
您好，请教您一下。我在腾讯云 Serverless 中，上传了您的代码之后，点击完成时，提示“上传失败，请在高级配置中填写启动命令”，请问启动命令应该填什么？

感谢

**Comment by avtion** [comment]
emm，需要使用到的是腾讯云`函数服务`而并非完整的`serverless`服务，在函数服务中并不需要提供启动命令

**Comment by avtion** [comment]
![截屏2021-07-19 00 31 50](https://user-images.githubusercontent.com/34846850/126074998-1437d7c3-0fe9-40c5-9dd1-3da75ce4082d.png)

**Comment by beader** [comment]
部署成功了。但是推送的时候会提示 {"code": 400, "message": "failed to get token from env"}

**Comment by avtion** [comment]
[发送消息提示failed to get token from env](https://github.com/avtion/bark-serverless#%EF%B8%8F-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)

**Comment by beader** [comment]
感谢。明白了，相当于这个把 token 存在环境变量中了。这么做的话，这个 server 就只能一个人使用咯？

**Comment by avtion** [comment]
> 感谢。明白了，相当于这个把 token 存在环境变量中了。这么做的话，这个 server 就只能一个人使用咯？

目前来说，是的。应用场景就是一个人用，如果要多个人的话就需要专门配置数据库了，这个需求可以加TODO

**Comment by beader** [comment]
嗯嗯，我昨天用 cloudbase 云托管来部署，用是可以用，但是服务休眠重启后，会启动新的容器，原来的 /data 就没了。这个可以靠挂载 cfs 来解决。但腾讯的[文档](https://cloud.tencent.com/document/product/1243/53624)看起来好吃力。
