### ISSUE TITLE
可以更新下版本吗。。

### ISSUE THREAD

**Issue by dudt** [avtion/bark-serverless#2]
可以更新下版本吗。。

**Comment by avtion** [comment]
更新版本是指？目前实测 **Bark 1.2.0** 是可用的

**Comment by dudt** [comment]
> 更新版本是指？目前实测 **Bark 1.2.0** 是可用的

我看官方都更新到2.02了。。

**Comment by avtion** [comment]
- 你指的是 [Finb/bark-server](https://github.com/Finb/bark-server) 这个项目吧？这个是服务端，目前版本是 2.0.2，我目前项目依赖的服务端版本就是 2.0.2，已经是最新的 tag 了，具体可以查看 [go.mod](https://github.com/avtion/bark-serverless/blob/master/go.mod#L7) 文件 (即当前 bark-serverless 1.0.0 已经是 bark-server 发行版 2.0.2 的代码)
- bark-serverless 目前是兼容客户端 1.2.0 版本的，除了 `分组发送功能`，`分组发送功能`需要依赖服务端 master 分支，目前 feature/1.1.0 分支已经支持了，等我完善一下文档就可以发了

**Comment by dudt** [comment]
> * 你指的是 [Finb/bark-server](https://github.com/Finb/bark-server) 这个项目吧？这个是服务端，目前版本是 2.0.2，我目前项目依赖的服务端版本就是 2.0.2，已经是最新的 tag 了，具体可以查看 [go.mod](https://github.com/avtion/bark-serverless/blob/master/go.mod#L7) 文件 (即当前 bark-serverless 1.0.0 已经是 bark-server 发行版 2.0.2 的代码)
> * bark-serverless 目前是兼容客户端 1.2.0 版本的，除了 `分组发送功能`，`分组发送功能`需要依赖服务端 master 分支，目前 feature/1.1.0 分支已经支持了，等我完善一下文档就可以发了

这样啊！懂了谢谢

**Comment by dudt** [comment]
> > * 你指的是 [Finb/bark-server](https://github.com/Finb/bark-server) 这个项目吧？这个是服务端，目前版本是 2.0.2，我目前项目依赖的服务端版本就是 2.0.2，已经是最新的 tag 了，具体可以查看 [go.mod](https://github.com/avtion/bark-serverless/blob/master/go.mod#L7) 文件 (即当前 bark-serverless 1.0.0 已经是 bark-server 发行版 2.0.2 的代码)
> > * bark-serverless 目前是兼容客户端 1.2.0 版本的，除了 `分组发送功能`，`分组发送功能`需要依赖服务端 master 分支，目前 feature/1.1.0 分支已经支持了，等我完善一下文档就可以发了
> 
> 这样啊！懂了信息
